version: '3'

services:
  dev:
    image: tolacika/php
    user: 1000:1000
    ports:
      - 80:80
    build:
      context: .
    volumes:
      - ./:/var/www/html
  database:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: invitation
      MYSQL_PASSWORD: supersecret123
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: supersecret123
      MYSQL_USER: invitation
    volumes:
      - ./data:/var/lib/mysql
